#!/bin/bash

curl --header "Content-Type: application/json" --request POST --data '{"name": "Kelvur", "book": "A big lie"}' http://localhost:3000/users

curl http://localhost:3000/users

curl http://localhost:3000/logo.svg
